title: Praveen Kumar Pendyala
email:
description: >-
  Find out more about Praveen - his interests, skills, education, work, awards, projects and 
  his continious learning. Discover the topics he talks about in his blog.
twitter_username: praveendath92
github_username: praveendath92
minimal_mistakes_skin: air
search: true
breadcrumbs: true
repository: praveendath92/praveendath92.github.io
masthead_title: "PKP.io"
search_provider: google

# Search settings
google:
  search_engine_id: "011858246901281195939:-tnabjnwv3q"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /blog/:title/
timezone: GB

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Praveen Pendyala
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Software Engineer with eternal curiosity for anything technology and economics."
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/praveendath92

    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/praveendath92/

    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://instagram.com/praveendath92

    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/praveendath92

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/praveendath92

    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/praveendath92/

    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://instagram.com/praveendath92

    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/praveendath92

defaults:
  # default for all items
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /blog/categories/

tag_archive:
  type: liquid
  path: /blog/tags/

collections:
  education:
    output: true
    permalink: /:collection/:title/
  work:
    output: true
    permalink: /:collection/:title/
  talks:
    output: true
    permalink: /:collection/:title/
  papers:
    output: true
    permalink: /:collection/:title/
  awards:
    output: true
    permalink: /:collection/:title/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
