# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Praveen Kumar Pendyala
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: praveendath92
github_username: praveendath92
minimal_mistakes_skin: air
search: true
repository: praveendath92/praveendath92.github.io
masthead_title: "PKP.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /blog/:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: GB

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Praveen Pendyala
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Software Engineer with eternal curiosity for anything technology and economics."
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/praveendath92

    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/praveendath92/

    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://instagram.com/praveendath92

    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/praveendath92

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/praveendath92

    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/praveendath92/

    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://instagram.com/praveendath92

    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/praveendath92

defaults:
  # default for all items
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /blog/categories/

tag_archive:
  type: liquid
  path: /blog/tags/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
